VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IStorage"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get Events() As IStorageEvents
'
End Property

Public Function Add(ByVal pModel As IModel) As Long
'
End Function

Public Sub Remove(ByVal lIndex As Long)
'
End Sub

Public Function GetItems() As Collection
'
End Function

