VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IStorage"
Attribute VB_Base = "0{FCFB3D2A-A0FA-1068-A738-08002B3371B5}"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_TemplateDerived = False
Attribute VB_Customizable = False
Option Explicit

Public Property Get Events() As IStorageEvents
'
End Property

Public Function Add(ByVal pModel As IModel, Optional ByVal lIndex = -1) As Long
'
End Function

Public Sub Remove(ByVal lIndex As Long)
'
End Sub

Public Function GetItems() As Collection
'
End Function
